config/routes.rb
Rails.application.routes.draw do
  
  #resources :comments
  resources :tags
  resources :videos
  resources :reports do
    resources :comments
  end

  get 'comments/:id/edit_personification' => 'comments#edit_personification', as: :edit_personification
   
  get 'comments/update_personification'

  root 'home#index'
  get 'home/index'
  get 'home/manipulationusers'
  get 'home/new'
  get 'home/show_create'
  get 'home/show'
  get 'home/edit'

  get 'home/friends'

  get 'home/:id/show_update' => 'home#show_update', as: :show_update


  get 'home/:id/show_destroy' => 'home#show_destroy', as: :show_destroy

  #delete 'home/:id', controller: 'home', action: 'destroy' , as: 'destroy'

  get 'tags/:id/search_tag' => 'tags#search_tag', as: :search_tag



  devise_for :users

end

app/models/video.rb
class Video < ApplicationRecord
  has_many :tags

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:titulo, :rating)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for @video, :html => { :class => "form-horizontal video" } do |f| %>

  <% if @video.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @video.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:titulo) %>
  </div>
  <div class="form-group">
    <%= f.label :rating, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rating, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rating) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                videos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/videos/edit.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/index.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.id, video_path(video) %></td>
        <td><%= video.titulo %></td>
        <td><%= video.rating %></td>
        <td><%=l video.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      video_path(video), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_video_path(video), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      video_path(video),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_video_path,
            :class => 'btn btn-primary' %>

app/views/videos/new.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/show.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @video.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @video.rating %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              videos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_video_path(@video), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              video_path(@video),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>