config/routes.rb
Rails.application.routes.draw do
  
  #resources :comments
  resources :tags
  resources :videos
  resources :reports do
    resources :comments
  end

  get 'comments/:id/edit_personification' => 'comments#edit_personification', as: :edit_personification
   
  get 'comments/update_personification'

  root 'home#index'
  get 'home/index'
  get 'home/manipulationusers'
  get 'home/new'
  get 'home/show_create'
  get 'home/show'
  get 'home/edit'

  get 'home/friends'

  get 'home/:id/show_update' => 'home#show_update', as: :show_update


  get 'home/:id/show_destroy' => 'home#show_destroy', as: :show_destroy

  #delete 'home/:id', controller: 'home', action: 'destroy' , as: 'destroy'

  get 'tags/:id/search_tag' => 'tags#search_tag', as: :search_tag



  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit ]
  before_action :set_user2, only: [:show_update, :show_destroy]


def index
  @users = User.all
 # @reports = Report.all
  @tags = Tag.all 
  @videos = Video.all
  #authorize @users
 #puts "user_signed_in.user #{user_signed_in.email}"
 #puts "user_signed_in#{user_signed_in}"
  
 if params[:search]
  #@report = Report.where("titulo like '%#{params[:search]}%'") 
      
        #ou assim que eh mais indicado pela comunidade:
     @report = Report.where("titulo like ?", "%#{params[:search][:titulo]}%")          

  else
    @report = Report.all 
  end



 # @user = User.new
 # authorize @user
end

def friends
   @friends = User.where(role: 1)
end

def manipulationusers
     
   @users = User.all
  
end 


def new
    # @user = User.new
    # authorize @user
end

def show
end

def show_create
  
   if User.find_by(email: params[:@user][:email].strip).nil?
        @iqual = 1
       
      @iqual=0
      @user = User.new(user_params)
      @role = params[:@user][:role]
      #id.to_i
      @role = @role.to_i
      #respond_to do |format|
        if @user.save(validate: false)
          @user.role =@role
          @user.save(validate: false)
          flash[:error] = ""
          flash[:notice] = "Usuario criado com sucessoo!"
          
          # format.html { redirect_to @user, notice: 'Report was successfully created.' }
        # format.json { render :show, status: :created, location: @user }
        else
          #format.html { render :new }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
            render :new
        end
      #end
    else
      flash[:error] = "Erro! Conta ja existe!"
      #render :new 
       redirect_to home_new_path
    end  

end

def edit

end


def show_update
  @quarda = user_params
  puts "valor do user_params #{@quarda}"
  #puts "params titulo = #{params[:user][:email]}"  
  
  #@user.email = params[:user][:email]
  #@user.password = params[:user][:password]
  #@user.password_confirmation = params[:user][:password_confirmation]
  @user.role = params[:@user][:role].to_i
  @user.name = params[:@user][:name]
  
  #respond_to do |format|
    if @user.save(validate: false)
      #format.html { redirect_to @user, notice: 'Report was successfully updated.' }
      flash[:notice] = "Credenciais do usuario 
          {#{@user.name}} atualizada com sucesso!"
          
      # format.json { render :show, status: :ok, location: @user }
    else
       render :edit
     # format.html { render :edit }
     # format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  
end


def show_destroy
  @userbanido = @user
  @user.destroy
  flash[:notice] = "O usuario 
    {#{@userbanido.name}} foi excluido com sucesso!"

  
end



private

  def set_user
     puts "valor da params #{params} e #{params[:id]}"
     puts "valor params format #{params[:format]}"
     #cont = params[format].to.i
     @user = User.find(params[:format])
  end

  def set_user2
    puts "valor da params #{params} e #{params[:id]}"
    puts "valor params format #{params[:format]}"
    #cont = params[format].to.i
    @user = User.find(params[:id])
 end


  def user_params
     params.require(:@user).permit(:email, :password, :password_confirmation, :name)
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_user_index.html.erb
<div class="container" style="margin-top:0px; padding-left: 1px" >
       
<div class="d-flex align-items-end"  style="margin-top:-22px; padding-left: 250px; margin-left: 7px;">
    
    <div class="col-md-2" style="margin-top: 10px; padding-left: 27px; ">       
        <%= link_to "Noticias", reports_path,  class: "btn btn-success" %>  
    </div>
    
    <div class="col-md-2" style="margin-top: 10px; padding-left: 23px; margin-right: -5px ">       
        <%= link_to "Tags",  tags_path,  class: "btn btn-danger" %>  
    </div>
  

    <div class="col-md-2" style="margin-top: 10px; padding-left: 7px;  ">       
        <%= link_to "Videos",  videos_path,  class: "btn btn-warning" %>  
    </div>
    
   

    <div class="col-md-2" style="margin-top: 10px; padding-left: 2px;  ">       
       <%= link_to "Usuarios",  home_manipulationusers_path,  class: "btn btn-primary" %>  
    </div>

</div>

app/views/home/_form.html.erb
 

<%= form_for :@user , url: show_update_path(@user.id) , html: {method: "get", role: "form", class: "col-md-8", style: "padding-left: 0px;"} do |a| %>

   

     <div class="form-group" style= "width: 350px; padding-left: 15px">
        <%= a.label :role, "função (0 para admin ou 1 para comum)  * :",  class: 'required', style:"font-size: 15px;" %>
        <%= a.text_field :role, value: @user.role, class: "form-control" %>
     </div>


     
     <div class="form-group" style= "width: 350px; padding-left: 15px">
       <%= a.label :name, "nome* :",  class: 'required', style:"font-size: 15px;" %>
        <%= a.text_field :name, value: @user.name,  class: "form-control" %>
     </div>


    <div class="form-group" style="padding-left: 15px" >     
      <%= a.submit "Atualizar Credenciais", class: "btn btn-primary" %>
      
    </div>


<% end %>











  
  
    

app/views/home/_normal_user_index.html.erb
<p style="padding-left: 37px; margin-bottom: 1px; font-weight: bolder; font-size: 20px"> noticias :</p>

  <%= form_for :search, url: root_path, html: {method: "get", role: "form", class: "col-md-8", style: "padding-left: 0px;  "} do |f| %>

    
    <div class="container" >

        <div class="d-flex align-items-end", style="margin-top: -40px;" >

                         
                <div class="col-md-2" style="margin-top: 5px; padding-left: 17px;">
                   <%= f.text_field :titulo, class: "form-control", required: "true"  %>
                </div>
                <div class="col-md-4" style="margin-top: 5px;  ">  
                   <%= f.submit "Pesquisar", class: "btn btn-primary " %>
                </div>

          <div>
      </div> 
      
  <%end%>

<%- model_class = User  -%>
<div class="page-header">
  <h2 style="margin-top: 50px">noticias</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:informacões) %></th>
    
    </tr>
  </thead>
  <tbody>
    <% @report.each do |report| %>
      <tr>
        <td><%= report.titulo %></td>
        <td><%= report.information %></td>
        
        
        
        <td>
          <%= link_to t('.comentar', :default => t("helpers.links.comentar")),
             new_report_comment_path(report.id), :class => 'btn btn-xs btn-success' %>
            
          <%= link_to t('.vê comentarios', :default => t("helpers.links.vê comentarios")),
             report_comments_path(report.id), :class => 'btn btn-xs btn-info' %>  
          
             
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="col-md-2" style="margin-top: 23px; padding-left: 5px; margin-right: 600px  ">       
    <%= link_to "Criar Usuario", home_new_path,  class: "btn btn-primary" %>  
</div>

app/views/home/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edicao de Usuario'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/home/friends.html.erb
<%- model_class = User  -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:funcao) %></th>
      <th><%=t '.ação', :default => t("helpers.ação") %></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        
        
        <td>
          <%= link_to t('.exibir', :default => t("helpers.links.exibir")),
                  home_show_path(user.id), :class => 'btn btn-xs btn-success' %>
          
          
        
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<p2 style=" font-size: 17px; margin-top:5px; margin-left: 1100px; background-color: #05ffb0;"> <%= link_to "Sair",destroy_user_session_path, method: :delete %> </p2>
                            
<% if policy(@users).index? %>
     
    <%= render partial: "admin_user_index" %>

   
        
 <%else%>                    
       <%= render partial: "normal_user_index" %>
<%end%>

app/views/home/manipulationusers.html.erb
<div class="col-md-2" style="margin-top: 0px; padding-left: 740px;  ">       
    <%= link_to "Criar Usuario", home_new_path,  class: "btn btn-primary" %>  
</div>






<%- model_class = User  -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:funcao) %></th>
      <th><%=t '.ação', :default => t("helpers.ação") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        
        
        <td>
          <%= link_to t('.exibir', :default => t("helpers.links.exibir")),
                  home_show_path(user.id), :class => 'btn btn-xs btn-success' %>
          
          
          <% if policy(@users).index? %>        
                  
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                home_edit_path(user.id), :class => 'btn btn-xs btn-warning' %> 
           
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                show_destroy_path(user.id),
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza que deseja excluir?')) },
                :class => 'btn btn-xs btn-danger' %>    
        
          <%end%>
      
          </td>
      </tr>
    <% end %>
  </tbody>
</table>





<%= link_to t('.new', :default => t("helpers.links.new")),
            new_report_path,
            :class => 'btn btn-primary' %>

app/views/home/new.html.erb
 
<h2 style="margin-top: -5px;margin-left: 333px;font-weight: bold; font-size: 25px"> PAGINA DE CRIACAO DE USUARIO<h2>

<%= form_for :@user , url: home_show_create_path , html: {method: "get", role: "form", class: "col-md-8", style: "padding-left: 0px;"} do |a| %>
    <div class="form-group" style= "width: 350px; padding-left: 15px">
       <%= a.label :email, "email* :",  class: 'required', style:"font-size: 15px;" %>
        <%= a.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group" style= "width: 350px; padding-left: 15px">
       <%= a.label :password, "senha* :",  class: 'required', style:"font-size: 15px;" %>
        <%= a.text_field :password, class: "form-control" %>
     </div>

     <div class="form-group" style= "width: 350px; padding-left: 15px">
       <%= a.label :password_confirmation, "confirmacao de senha* :",  class: 'required', style:"font-size: 15px;" %>
       <%= a.text_field :password_confirmation, class: "form-control" %>
     </div>

     <div class="form-group" style= "width: 350px; padding-left: 15px">
        <%= a.label :role, "função (0 para admin ou 1 para comum)  * :",  class: 'required', style:"font-size: 15px;" %>
        <%= a.text_field :role, class: "form-control" %>
     </div>


     
     <div class="form-group" style= "width: 350px; padding-left: 15px">
       <%= a.label :name, "nome* :",  class: 'required', style:"font-size: 15px;" %>
        <%= a.text_field :name, class: "form-control" %>
     </div>


    <div class="form-group" style="padding-left: 15px" >     
      <%= a.submit "Criar User", class: "btn btn-primary" %>
      
    </div>


<% end %>

app/views/home/show.html.erb
<h2> Resumo do Usuario</h2>

    <%- model_class = User -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dd><%= @user.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @user.role %></dd>
</dl>



<%= link_to t('.Voltar', :default => t("helpers.links.Voltar")),
    home_manipulationusers_path, :class => 'btn btn-default', style:"color: blue;"  %>  

app/views/home/show_create.html.erb
<h2> Resumo do Usuario</h2>

    <%- model_class = User -%>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @user.role %></dd>
</dl>



<%= link_to t('.Voltar', :default => t("helpers.links.Voltar")),
    home_manipulationusers_path, :class => 'btn btn-default', style:"color: blue;"  %>  

app/views/home/show_destroy.html.erb
<%= link_to t('.Voltar', :default => t("helpers.links.Voltar")),
    home_manipulationusers_path, :class => 'btn btn-default', style:"color: blue;"  %>  

app/views/home/show_update.html.erb
<h2>  Atualizacao de usuario</h2>

<%- model_class = User -%>

<dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @user.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
    <dd><%= @user.role %></dd>
</dl>



<%= link_to t('.Voltar', :default => t("helpers.links.Voltar")),
    home_manipulationusers_path, :class => 'btn btn-default', style:"color: blue;"  %>  