config/routes.rb
Rails.application.routes.draw do
  
  #resources :comments
  resources :tags
  resources :videos
  resources :reports do
    resources :comments
  end

  get 'comments/:id/edit_personification' => 'comments#edit_personification', as: :edit_personification
   
  get 'comments/update_personification'

  root 'home#index'
  get 'home/index'
  get 'home/manipulationusers'
  get 'home/new'
  get 'home/show_create'
  get 'home/show'
  get 'home/edit'

  get 'home/friends'

  get 'home/:id/show_update' => 'home#show_update', as: :show_update


  get 'home/:id/show_destroy' => 'home#show_destroy', as: :show_destroy

  #delete 'home/:id', controller: 'home', action: 'destroy' , as: 'destroy'

  get 'tags/:id/search_tag' => 'tags#search_tag', as: :search_tag



  devise_for :users

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :report
  belongs_to :video

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  def search_tag
      puts "tagsssss #{params[:id]}"
      @tag = Tag.find(params[:id])
      @reports = Report.where(id: @tag.report_id)
     
      @users = User.all
      
  end  

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save(validate: false)
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    
    @tag.name = params[:tag][:name]
    @tag.lingua = params[:tag][:lingua]
    @tag.report_id = params[:tag][:report_id]
    
    respond_to do |format|
      if @tag.save(validate: false)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name, :lingua, :report_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => { :class => "form-horizontal tag" } do |f| %>

  <% if @tag.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :lingua, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lingua, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lingua) %>
  </div>
  <div class="form-group">
    <%= f.label :report_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10" , style="margin-top: 7px">
     <%=select("tag", "report_id", Report.all.collect {|r| [ r.titulo, r.id ] }, {prompt: 'Selecione o assunto da tag'})%> 

    </div>
    <%=f.error_span(:report_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tags_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tags/edit.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tags/index.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:lingua) %></th>
      <th><%= model_class.human_attribute_name(:criada_em) %></th>
      
    </tr>
  </thead>
  
  <tbody>
    <% @tags.each do |tag| %>
     <% id = tag.report_id %>
      <tr>
       <td><li style="color:blue; background-color: rgba(50, 115, 220, 0.3);"><%= link_to tag.name, search_tag_path(tag) %></li></td>
        <td><%= tag.lingua %></td>
        <td><%=l tag.created_at %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      tag_path(tag), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tag_path(tag), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tag_path(tag),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tag_path,
            :class => 'btn btn-primary' %>

app/views/tags/new.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tags/search_tag.html.erb
<h2> tags search</h2>



<%- model_class = Report -%>
<div class="page-header">
 <h2> Notícias</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:rated) %></th>
      <th><%= model_class.human_attribute_name(:information) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
     
        <td><%= report.titulo %></td>
        <td><%= report.rating %></td>
        <td><%= report.rated %></td>
        <td><%= report.information %></td>
        <td><%= report.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      report_path(report), :class => 'btn btn-warning btn-xs' %>
          
          
          <% if policy(@users).index? %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_report_path(report), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          report_path(report),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
        
          <%end%>               
        
         </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_report_path,
            :class => 'btn btn-primary' %>

app/views/tags/show.html.erb
<%- model_class = Tag -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @tag.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lingua) %>:</strong></dt>
  <dd><%= @tag.lingua %></dd>
  <dt><strong><%= model_class.human_attribute_name(:report_id) %>:</strong></dt>
  <dd><%= @tag.report_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tags_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tag_path(@tag), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tag_path(@tag),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>