config/routes.rb
Rails.application.routes.draw do
  
  #resources :comments
  resources :tags
  resources :videos
  resources :reports do
    resources :comments
  end

  get 'comments/:id/edit_personification' => 'comments#edit_personification', as: :edit_personification
   
  get 'comments/update_personification'

  root 'home#index'
  get 'home/index'
  get 'home/manipulationusers'
  get 'home/new'
  get 'home/show_create'
  get 'home/show'
  get 'home/edit'

  get 'home/friends'

  get 'home/:id/show_update' => 'home#show_update', as: :show_update


  get 'home/:id/show_destroy' => 'home#show_destroy', as: :show_destroy

  #delete 'home/:id', controller: 'home', action: 'destroy' , as: 'destroy'

  get 'tags/:id/search_tag' => 'tags#search_tag', as: :search_tag



  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "InformationNews" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
   
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
   
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
   
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
   
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    
    <div class="navbar navbar-default navbar-static-top" style="margin-top: -32px">
      <div class="container" >
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Novidades do Dia</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Inicio", root_path  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          <%if user_signed_in?%> 
            <li style="margin-left: 680px; padding-top: 15px; color: #436EEE "><%=current_user.email%> </li>
          <%end%>
            </ul>
        </div>
      </div>
    </div>


    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Menu</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Usuarios", home_manipulationusers_path  %></li>
              <li><%= link_to "Tags", tags_path  %></li>
              <li><%= link_to "Videos", videos_path  %></li>
              <li><%= link_to "Notícias", reports_path  %></li>
              <li><%= link_to "Amigos", home_friends_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->
   
      <footer>
        <p style="margin-top: 433px;">&copy; Melhor Empresa Ti:Envixo 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>